CREATE TABLE IF NOT EXISTS faq (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'FAQ ID',
  question VARCHAR(500) NOT NULL COMMENT '问题',
  answer TEXT NOT NULL COMMENT '答案',
  keywords VARCHAR(500) NULL COMMENT '关键词，逗号分隔',
  category VARCHAR(100) NULL COMMENT '分类',
  hit_count INT NOT NULL DEFAULT 0 COMMENT '命中次数',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',

  PRIMARY KEY (id),
  KEY idx_faq_hit_count (hit_count),
  KEY idx_faq_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FAQ 知识库表';
